In [4]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
sum_list=[]
print("concat",lst1+lst2)
for i,j in zip(lst1,lst2):
  sum_list.append(i+j)

sum_list

concat [1, 2, 3, 4, 5, 6, 7, 8]


[6, 8, 10, 12]

In [10]:
import numpy as np
arr1=np.array(lst1)
arr2=np.array(lst2)
arr1
arr2
sum_list=arr1+arr2
sum_list

array([ 6,  8, 10, 12])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1.ndim

1

In [17]:
lst3=[[2,1,4,],[3,6,7]]
arr3=np.array(lst3)
arr3.ndim

2

In [18]:
arr3.shape


(2, 3)

In [27]:
arr4=np.arange(6)
arr4

array([0, 1, 2, 3, 4, 5])

In [28]:
arr5=arr4.reshape(2,3)                  
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
arr4.sum()

15

In [31]:
arr4.mean()

2.5

In [32]:
np.median(arr4)

2.5

In [33]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.random.rand(3,4)

array([[0.88437338, 0.52197463, 0.17434596, 0.63731554],
       [0.52230677, 0.25902897, 0.53680331, 0.89934524],
       [0.4825947 , 0.00738986, 0.98932053, 0.5378187 ]])

Pandas

In [39]:
import pandas as pd
data=pd.read_csv('//content/auto-mpg.csv')
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]